import './fixtures/omni-network.mjs';
import assert from 'node:assert/strict';
import { startUiV2Session, prepareUiV2Page, switchUiV2View } from './ui_v2_helpers.mjs';
const session = await startUiV2Session();
try {
  const context = await session.createContext();
  const { page, pageErrors } = await prepareUiV2Page(context, session.server.baseUrl);
  await switchUiV2View(page, 'financial');
  await page.locator('#newFinancialEntryButton').click();
  await page.locator('#finLinkSearch').fill('Escritório');
  await page.locator('#finLinkSearch').press('Enter');
  assert.equal(await page.locator('#finLinkSearch').getAttribute('aria-expanded'), 'false');
  await page.locator('#finTypeSelect').selectOption('despesa');
  await page.locator('#finDescriptionInput').fill('Aluguel sintético');
  await page.locator('#finGrossInput').fill('850');
  await page.locator('#financialEntryForm button[type="submit"]').click();
  await page.locator('#financialEntryBackdrop.hidden').waitFor({ state: 'attached' });
  assert.equal(await page.evaluate(() => window.Atrium.Store.state.officeExpenses.at(-1).amount), 850);
  await page.reload();
  await page.waitForFunction(() => Boolean(window.Atrium?.Store?.state?.officeExpenses?.length));
  assert.equal(await page.evaluate(() => window.Atrium.Store.state.officeExpenses.at(-1).description), 'Aluguel sintético');
  await switchUiV2View(page, 'financial');
  assert.match(await page.locator('#financialV2Workspace').textContent(), /Aluguel sintético/);
  assert.ok(await page.locator('#financialV2Workspace .financial-process-link.is-static').count() > 0);
  assert.equal(await page.locator('#financialV2Workspace button.financial-process-link[disabled]').count(), 0);
  assert.equal(await page.locator('#financialV2Workspace .financial-process-link.is-static [aria-hidden]').count(), 0);
  await page.locator('#newFinancialEntryButton').click();
  assert.equal(await page.locator('#finLinkSearch').inputValue(), '');
  assert.equal(await page.locator('#finLinkSearch').getAttribute('aria-expanded'), 'false');
  await page.locator('#financialEntryCancel').click();
  await page.evaluate(async () => {
    window.Atrium.Store.state.contacts.push({ id: 'finance-contact', name: 'Cliente Financeiro Sintético', contactRole: 'cliente' });
    window.Atrium.Store.save();
    if (!await window.Atrium.Store.flush()) throw Error('Synthetic fixture was not saved');
  });
  await page.locator('#newFinancialEntryButton').click();
  await page.locator('#finLinkSearch').fill('Cliente Financeiro Sintético');
  await page.locator('#finLinkSearch').press('Enter');
  assert.equal(await page.locator('#finProcessSelect').inputValue(), 'contact:finance-contact');
  await page.locator('#finTypeSelect').selectOption('recebimento');
  await page.locator('#finGrossInput').fill('120');
  await page.locator('#financialEntryForm button[type="submit"]').click();
  await page.locator('#financialEntryBackdrop.hidden').waitFor({ state: 'attached' });
  await page.reload();
  await page.waitForFunction(() => window.Atrium?.Store?.state?.contacts?.some(c => c.id === 'finance-contact' && c.receipts?.length === 1));
  assert.equal(await page.evaluate(() => window.Atrium.Store.state.contacts.find(c => c.id === 'finance-contact').receipts[0].amount), 120);
  assert.deepEqual(pageErrors, []);
  await switchUiV2View(page, 'financial');
  const originalExpense = await page.evaluate(() => window.Atrium.Store.state.officeExpenses[0]);
  await page.locator('.financial-v2-table [data-financial-record]').filter({ hasText: 'Aluguel sintético' }).click();
  assert.equal(await page.locator('#finModalTitle').textContent(), 'Editar lançamento financeiro');
  assert.equal(await page.locator('#finGrossInput').inputValue(), '850');
  assert.ok(await page.locator('#financialExpenseSuggestions option').count() >= 30);
  await page.locator('#finDescriptionInput').fill('Salários');
  await page.locator('#finGrossInput').fill('950');
  await page.locator('#finStatusSelect').selectOption('pago');
  await page.locator('#financialEntryForm button[type="submit"]').click();
  await page.locator('#financialEntryBackdrop.hidden').waitFor({ state: 'attached' });
  await page.reload();
  await page.waitForFunction(() => window.Atrium?.Store?.state?.officeExpenses?.[0]?.amount === 950);
  const updatedExpenses = await page.evaluate(() => window.Atrium.Store.state.officeExpenses);
  assert.equal(updatedExpenses.length, 1);
  assert.equal(updatedExpenses[0].id, originalExpense.id);
  assert.equal(updatedExpenses[0].createdAt, originalExpense.createdAt);
  assert.equal(updatedExpenses[0].description, 'Salários');
  assert.equal(updatedExpenses[0].status, 'pago');
  await switchUiV2View(page, 'financial');
  const receiptId = await page.evaluate(() => window.Atrium.Store.state.contacts.find(c => c.id === 'finance-contact').receipts[0].id);
  await page.locator(`.financial-v2-table [data-financial-record="${receiptId}"]`).focus();
  await page.keyboard.press('Enter');
  assert.equal(await page.locator('#finGrossInput').inputValue(), '120');
  await page.locator('#finGrossInput').fill('135');
  await page.evaluate(() => { window.__originalFinancialFlush = window.Atrium.Store.flush; window.Atrium.Store.flush = async () => false; });
  await page.locator('#financialEntryForm button[type="submit"]').click();
  await page.waitForFunction(() => !document.querySelector('#financialEntryForm button[type="submit"]').disabled);
  assert.equal(await page.locator('#financialEntryBackdrop:not(.hidden)').count(), 1);
  assert.equal(await page.evaluate(() => window.Atrium.Store.state.contacts.find(c => c.id === 'finance-contact').receipts[0].amount), 120);
  await page.evaluate(() => { window.Atrium.Store.flush = window.__originalFinancialFlush; delete window.__originalFinancialFlush; });
  await page.locator('#financialEntryForm button[type="submit"]').click();
  await page.locator('#financialEntryBackdrop.hidden').waitFor({ state: 'attached' });
  await page.reload();
  await page.waitForFunction(() => window.Atrium?.Store?.state?.contacts?.find(c => c.id === 'finance-contact')?.receipts?.[0]?.amount === 135);
  const receipts = await page.evaluate(() => window.Atrium.Store.state.contacts.find(c => c.id === 'finance-contact').receipts);
  assert.equal(receipts.length, 1);
  assert.equal(receipts[0].id, receiptId);
  await switchUiV2View(page, 'financial');
  await page.locator(`.financial-v2-table [data-financial-record="${originalExpense.id}"]`).click();
  assert.equal(await page.locator('#finLinkSearch').isEnabled(), true);
  await page.locator('#finLinkSearch').fill('Cliente Financeiro Sintético');
  await page.locator('#finLinkSearch').press('Enter');
  await page.locator('#finDateInput').fill('2026-09-01');
  await page.locator('#financialEntryForm button[type="submit"]').click();
  await page.locator('#financialEntryBackdrop.hidden').waitFor({ state: 'attached' });
  await page.reload();
  await page.waitForFunction(() => window.Atrium?.Store?.state?.contacts?.find(c => c.id === 'finance-contact')?.expenses?.length === 1);
  assert.equal(await page.evaluate(() => window.Atrium.Store.state.officeExpenses.length), 0);
  const moved = await page.evaluate(() => window.Atrium.Store.state.contacts.find(c => c.id === 'finance-contact').expenses[0]);
  assert.equal(moved.id, originalExpense.id);
  assert.equal(moved.createdAt, originalExpense.createdAt);
  assert.equal(moved.date, '2026-09-01');
  await switchUiV2View(page, 'financial');
  await page.locator(`.financial-v2-table [data-financial-record="${originalExpense.id}"]`).click();
  await page.locator('#financialEntryDelete').click();
  await page.locator('[data-delete-cancel]').click();
  await page.locator('#financialDeleteConfirm').waitFor({ state: 'detached' });
  assert.equal(await page.evaluate(() => window.Atrium.Store.state.contacts.find(c => c.id === 'finance-contact').expenses.length), 1);
  await page.locator('#financialEntryDelete').click();
  await page.keyboard.press('Escape');
  await page.locator('#financialDeleteConfirm').waitFor({ state: 'detached' });
  assert.equal(await page.locator('#financialEntryBackdrop:not(.hidden)').count(), 1);
  await page.evaluate(() => { window.__originalFinancialFlush = window.Atrium.Store.flush; window.Atrium.Store.flush = async () => false; });
  await page.locator('#financialEntryDelete').click();
  await page.locator('[data-delete-confirm]').click();
  await page.waitForFunction(() => !document.getElementById('financialEntryDelete').disabled);
  assert.equal(await page.evaluate(() => window.Atrium.Store.state.contacts.find(c => c.id === 'finance-contact').expenses.length), 1);
  assert.equal(await page.locator('#financialEntryBackdrop:not(.hidden)').count(), 1);
  await page.evaluate(() => { window.Atrium.Store.flush = window.__originalFinancialFlush; delete window.__originalFinancialFlush; });
  await page.locator('#financialEntryDelete').click();
  await page.locator('[data-delete-confirm]').click();
  await page.locator('#financialEntryBackdrop.hidden').waitFor({ state: 'attached' });
  await page.reload();
  await page.waitForFunction(() => window.Atrium?.Store?.state?.contacts?.find(c => c.id === 'finance-contact')?.expenses?.length === 0);
  assert.equal(await page.evaluate(() => window.Atrium.Store.state.contacts.find(c => c.id === 'finance-contact').receipts.length), 1);
  assert.deepEqual(pageErrors, []);
  await switchUiV2View(page, 'financial');
  await page.locator('#newFinancialEntryButton').click();
  await page.locator('#finLinkSearch').fill('Escritório');
  await page.locator('#finLinkSearch').press('Enter');
  await page.locator('#finTypeSelect').selectOption('despesa');
  await page.locator('#finDescriptionInput').fill('Tipo incorreto sintético');
  await page.locator('#finGrossInput').fill('20');
  await page.locator('#financialEntryForm button[type="submit"]').click();
  await page.locator('#financialEntryBackdrop.hidden').waitFor({ state: 'attached' });
  const correctionId = await page.evaluate(() => window.Atrium.Store.state.officeExpenses[0].id);
  await page.locator(`.financial-v2-table [data-financial-record="${correctionId}"]`).click();
  await page.locator('#finLinkSearch').fill('Cliente Financeiro Sintético');
  await page.locator('#finLinkSearch').press('Enter');
  await page.locator('#finTypeSelect').selectOption('recebimento');
  await page.locator('#financialEntryForm button[type="submit"]').click();
  await page.locator('#financialEntryBackdrop.hidden').waitFor({ state: 'attached' });
  await page.reload();
  await page.waitForFunction(() => window.Atrium?.Store?.state?.contacts?.find(c => c.id === 'finance-contact')?.receipts?.length === 2);
  assert.equal(await page.evaluate(() => window.Atrium.Store.state.officeExpenses.length), 0);
  assert.equal(await page.evaluate(id => window.Atrium.Store.state.contacts.find(c => c.id === 'finance-contact').receipts.some(r => r.id === id && r.amount === 20), correctionId), true);
  await context.close();
  console.log('PASS office expense persistence, reload, search and reopening');
} finally { await session.stop(); }
